---
name: Log-Log4perl-AutoCategorize
version: 0.03_51
author: ~
abstract: extended Log::Log4perl logging
license: perl
requires:
  B::Generate: 1.06_01
  optimizer: 0.05_01
  perl: 5.8.0
recommends:
  Devel::Size: 0
provides:
  Devel::Size:
    file: lib/Log/Log4perl/AutoCategorize.pm
    version: 0.03_51
  Log::Log4perl::AutoCategorize:
    file: lib/Log/Log4perl/AutoCategorize.pm
    version: 0.03_51
generated_by: Module::Build version 0.2608
